site:
  title: Docs Site
  start_page: ctvision::about-ct-vision.adoc
content:
  sources:
  - url: git@github.com:vbelyakov-ct/docs.git
    branches: main
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
