Here you find a feature, the link to the corresponding article, and the
version of CT Mobile since which the feature is available.

== == == == * Vision for CT Mobile 2.9] * Vision for CT Mobile 2.6] * Vision for CT Mobile 2.5] *
Vision for CT Mobile 2.4]

== [[h2_1172874714]] CT Vision for CT Mobile 2.9
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

* CT Vision Lite, the new comprehensive solution to process photos while
working in the CT Mobile app for iOS users. CT Vision Lite includes the
server application responsible for storing photos without recognition,
managing them by tags and shelves, planning the number of photos to take
for the shelf.

== 
* Photos made in CT Vision are now stored in Salesforce in the new https://help.customertimes.com/smart/project-ct-vision-lite-en/vision-photo-field-reference-lite[Vision Photo] object. * You can now view photos taken for selected object record and its child records. * You can view photo tags while viewing photos in the
gallery].
* The
https://help.customertimes.com/articles/ct-vision-lite-en/working-with-ct-vision-lite-in-the-ct-mobile-app-2-9/a/h3__585482629[Simple
View] mode is added.  If enabled, the report data and the final summary
report will not be displayed
and https://help.customertimes.com/articles/ct-vision-lite-en/working-with-ct-vision-lite-in-the-ct-mobile-app-2-9/a/h2_566778463[previewing
pictures in full size] will be disabled.  

== [[h2_1172874713]] CT Vision for CT Mobile 2.6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[h3_110293510]]
Image Recognition
=== Tools
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Use
=== the
Product List] functionality to review recognized products on the
shelves.
** The ability to use up to 3 custom fields to display with the help of
the *Vision Product List* record type of _CTM Settings_.
** The *Product Info* and *Facing* columns are displayed by default.
** The ability to specify if the field should be editable. The
corrections will be sent per product and per shelf.
* A new *Pictures* section is displayed on the corresponding _Account_
record screen if at least one photo is made with CT Vision during the
visit.

[[h3_1379605186]]
CG Cloud
=== Support
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Connect to the CG Cloud image recognition provider.
* Perform a
https://help.customertimes.com/smart/project-ct-mobile-en/managing-visits-to-retail-stores/a/h3__481270469[Planogram
Check] task within a visit to retail stores.
* Calculate KPI for the shelves. 

== [[h2_1172874716]] CT Vision for CT Mobile 2.5
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[h3__489916585]]
Image Recognition
=== Tools
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

== 
== * customized], add one or more tags to the taken photo. ** Tap a photo in the *Miniatures* gallery
add one or more tags].
** Review photos with tags in the *Miniatures* gallery.

== == * link:vision-hint-field-reference.html[If specified], a mobile user will see product tips === the clickable realogram]. * new Collection mode] instead of the *Panorama* mode allows mobile users to take photos of large shelves. **
models] are supported in the *Collection* mode.

== 
[[h2_891547920]] CT Vision for CT Mobile 2.4
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[[h3_2077060874]]
Activation
=== 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

== * link:configuring-ct-mobile-for-work-with-ct-vision.html[Add CT Vision to the menu] to take photos and recognize products in the CT Mobile app. *
the CT Vision button] on the _Activity_ record to open the CT Vision
module.

[[h3_397932385]]
CT Vision
=== Module
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

During the sync process, photos of the _Activity_ records of the last 7
days will be downloaded on the mobile device.

[[h3_436277134]]
Image Recognition
=== Tools
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

== == * The *Standard Photo* and *Panorama* modes for taking photos of the products on the shelves. ** link:vision-shelf-field-reference.html[If specified], select the shelf type on the left side of the screen. ** link:vision-kpi-field-reference.html[Review shelf KPI]. ** Review recognized products === the clickable realogram]. * Manage photos in the *Miniatures* gallery. ** Photos are marked with color icons on the status]. ** In case of errors, delete, retake, or confirm a taken photo. *
a Report Summary] for the _Activity_ record to review the actual and
planned number of photos and shelf KPIs.

 +
